### ISSUE TITLE
InvocationTargetException when starting it up in Ubuntu

### ISSUE THREAD

**Issue by evjan** [relevance/labrepl#10]
When I install LabRepl using the command line guide in Ubuntu 10.04, I get the following output, and no REPL window (which I'm assuming will show up instead of the stack trace):

peter@fenix:~/clojure/labrepl$ script/repl 
Clojure 1.2.0-master-SNAPSHOT
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.encodings, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.helpers, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: compojure.http.request, being replaced by: #'clojure.contrib.duck-streams/spit
WARNING: spit already refers to: #'clojure.core/spit in namespace: user, being replaced by: #'clojure.contrib.io/spit
2010-05-28 22:23:21.056::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
solutions.mini_browser.proxy$javax.servlet.http.HttpServlet$0
2010-05-28 22:23:21.113::INFO:  jetty-6.1.21
2010-05-28 22:23:21.254::INFO:  Started SocketConnector@0.0.0.0:9000
labrepl.proxy$javax.servlet.http.HttpServlet$0
2010-05-28 22:23:21.259::INFO:  jetty-6.1.21
2010-05-28 22:23:21.287::INFO:  Started SocketConnector@0.0.0.0:8080
Welcome to the labrepl. Browse to localhost:8080 to get started!
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at jline.ConsoleRunner.main(ConsoleRunner.java:69)
Caused by: java.lang.IllegalStateException: javadoc already refers to: #'clojure.contrib.repl-utils/javadoc in namespace: user
    at clojure.lang.Namespace.warnOrFailOnReplace(Namespace.java:84)
    at clojure.lang.Namespace.reference(Namespace.java:107)
    at clojure.lang.Namespace.refer(Namespace.java:165)
    at clojure.core$refer.doInvoke(core.clj:3276)
    at clojure.lang.RestFn.applyTo(RestFn.java:140)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$load_lib.doInvoke(core.clj:4769)
    at clojure.lang.RestFn.applyTo(RestFn.java:143)
    at clojure.core$apply.invoke(core.clj:542)
    at clojure.core$load_libs.doInvoke(core.clj:4788)
    at clojure.lang.RestFn.applyTo(RestFn.java:138)
    at clojure.core$apply.invoke(core.clj:544)
    at clojure.core$use.doInvoke(core.clj:4868)
    at clojure.lang.RestFn.invoke(RestFn.java:409)
    at clojure.main$repl.doInvoke(main.clj:198)
    at clojure.lang.RestFn.invoke(RestFn.java:422)
    at clojure.main$repl_opt.invoke(main.clj:261)
    at clojure.main$main.doInvoke(main.clj:353)
    at clojure.lang.RestFn.invoke(RestFn.java:437)
    at clojure.lang.Var.invoke(Var.java:373)
    at clojure.lang.AFn.applyToHelper(AFn.java:169)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
    ... 5 more

**Comment by stuarthalloway** [comment]
Thanks! Should be fixed by http://github.com/relevance/labrepl/commit/5e7b95824c278e6ed93a008d6e0c6e8fdcfba56f
