### ISSUE TITLE
Error when trying to run script/repl

### ISSUE THREAD

**Issue by victorbstan** [relevance/labrepl#18]
Exception in thread "main" java.lang.ClassNotFoundException: clojure.main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at sun.misc.Launcher$ExtClassLoader.findClass(Launcher.java:229)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at jline.ConsoleRunner.main(Unknown Source)

when I run script/test it works fine though...

**Comment by abedra** [comment]
Did you run lein deps first?  The error you are getting is because clojure could not be found.  Try running lein deps then ./script/repl and things should work.

**Comment by victorbstan** [comment]
ok will try, thanks...
