### ISSUE TITLE
Error running repl script if not in labrepl home.

### ISSUE THREAD

**Issue by gstamp** [relevance/labrepl#35]
If I run the repl script from the labrepl home directory (by entering script/repl) everything works.

If I run the repl script from the the script directory (by entering ./repl) then I get the following error.

Exception in thread "main" java.lang.NoClassDefFoundError: jline/ConsoleRunner
Caused by: java.lang.ClassNotFoundException: jline.ConsoleRunner
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: jline.ConsoleRunner. Program will exit.

**Comment by abedra** [comment]
I would be happy to pull in a patch if you have or want to submit one, but for now I am going to leave this the way it is.
