### ISSUE TITLE
Problem with "lein deps"

### ISSUE THREAD

**Issue by Avram-zz** [relevance/labrepl#36]
Having trouble getting labrepl running.  There is a hidden problem of some kind that is causing "lein deps" to fail.  I am on a MacBook pro, 10.6.4.

msddpm2:~/projects/labrepl]  java -version
java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02-279-10M3065)
Java HotSpot(TM) 64-Bit Server VM (build 16.3-b01-279, mixed mode)
msddpm2:~/projects/labrepl]  lein version
Leiningen 1.4.0-SNAPSHOT on Java 1.6.0_20 Java HotSpot(TM) 64-Bit Server VM

msddpm2:~/projects/labrepl]  lein deps
Copying 56 files to /Users/aaelony/projects/labrepl/lib
Downloading: org/clojure/clojure/1.2.0-beta1/clojure-1.2.0-beta1.jar from clojure-snapshots
An error has occurred while processing the Maven artifact tasks.
 Diagnosis:
## Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)
## Exception in thread "main" Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

 (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:458)
    at clojure.lang.Var.invoke(Var.java:377)
    at clojure.lang.AFn.applyToHelper(AFn.java:174)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
## Caused by: Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

```
at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:175)
at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:678)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:265)
at leiningen.deps$deps.invoke(deps.clj:65)
at leiningen.deps$deps.invoke(deps.clj:73)
at leiningen.deps$deps.invoke(deps.clj:76)
at leiningen.deps$deps.invoke(deps.clj:77)
at clojure.lang.Var.invoke(Var.java:365)
at clojure.lang.AFn.applyToHelper(AFn.java:163)
at clojure.lang.Var.applyTo(Var.java:482)
at clojure.core$apply.invoke(core.clj:542)
at leiningen.core$apply_task.invoke(core.clj:158)
at leiningen.core$_main.doInvoke(core.clj:214)
at clojure.lang.RestFn.applyTo(RestFn.java:138)
at clojure.core$apply.invoke(core.clj:540)
at leiningen.core$_main.invoke(core.clj:219)
at user$eval168.invoke(NO_SOURCE_FILE:1)
at clojure.lang.Compiler.eval(Compiler.java:5424)
... 11 more
```
## Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

```
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:324)
at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:170)
... 33 more
```

**Comment by kbaribeau** [comment]
Hey, I just fixed this on my download by reverting to the version of Project.clj from yesterday.

**Comment by Avram-zz** [comment]
Hmmm, it still is broken for me.  Something in my environment may be causing this but I can't tell what it is. Btw, it installs fine on another computer I have without issue, just unfortunately not the one I want it on…

I have (repeatedly) tried the following:
1. remove  ~/.m2 directory
2. remove labrepl directory
3. remove lein 
4. git clone lein….
5. git clone labrepl…

What is the best way to start "fresh"  ??

This is what I currently see:

]  lein deps
Copying 56 files to /Users/aaelony/projects/labrepl/lib
Downloading: org/clojure/clojure/1.2.0-beta1/clojure-1.2.0-beta1.jar from clojure-snapshots
An error has occurred while processing the Maven artifact tasks.
 Diagnosis:

## Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

## Exception in thread "main" Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

 (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5369)
    at clojure.lang.Compiler.eval(Compiler.java:5320)
    at clojure.core$eval.invoke(core.clj:2366)
    at clojure.main$eval_opt.invoke(main.clj:233)
    at clojure.main$initialize.invoke(main.clj:252)
    at clojure.main$script_opt.invoke(main.clj:268)
    at clojure.main$main.doInvoke(main.clj:352)
    at clojure.lang.RestFn.invoke(RestFn.java:458)
    at clojure.lang.Var.invoke(Var.java:377)
    at clojure.lang.AFn.applyToHelper(AFn.java:174)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)

## Caused by: Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

```
at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:175)
at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:678)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:265)
at leiningen.deps$deps.invoke(deps.clj:65)
at leiningen.deps$deps.invoke(deps.clj:73)
at leiningen.deps$deps.invoke(deps.clj:76)
at leiningen.deps$deps.invoke(deps.clj:77)
at clojure.lang.Var.invoke(Var.java:365)
at clojure.lang.AFn.applyToHelper(AFn.java:163)
at clojure.lang.Var.applyTo(Var.java:482)
at clojure.core$apply.invoke(core.clj:538)
at leiningen.core$apply_task.invoke(core.clj:158)
at leiningen.core$_main.doInvoke(core.clj:214)
at clojure.lang.RestFn.applyTo(RestFn.java:138)
at clojure.core$apply.invoke(core.clj:536)
at leiningen.core$_main.invoke(core.clj:219)
at user$eval168.invoke(NO_SOURCE_FILE:1)
at clojure.lang.Compiler.eval(Compiler.java:5353)
... 11 more
```

## Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:

1) org.clojure:clojure:jar:1.2.0-beta1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-beta1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) autodoc:autodoc:jar:0.7.0
    3) org.clojure:clojure:jar:1.2.0-beta1

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  clojure (http://build.clojure.org/releases),
  clojars (http://clojars.org/repo/),
  clojure-snapshots (http://build.clojure.org/snapshots),
  clojure-releases (http://build.clojure.org/releases),
  central (http://repo1.maven.org/maven2)

```
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:324)
at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:170)
... 33 more
```

**Comment by kbaribeau** [comment]
Yup, I see the same thing.  This is what worked for me:

~/code/labrepl (master)$ git checkout 275bbf9221e98b70e16d782a6ff9d217d655a743 project.clj 

~/code/labrepl (master)$ lein deps

Copying 56 files to /Users/kbaribeau/code/labrepl/lib
Overriding previous definition of reference to labrepl
Overriding previous definition of reference to dependency.fileset
Copying 7 files to /Users/kbaribeau/code/labrepl/lib/dev
~/code/labrepl (master)$ lein repl

"REPL started; server listening on localhost:50359."
user=> 

It looks to me like a problem with the project.clj that's currently pushed up to github.  The checkins made on Friday afternoon seem to be broken, but when I use the above git checkout command to revert it to the version from Friday morning, it works.

**Comment by Avram-zz** [comment]
Cool.  I got past the previous issue as well by calling downloading the jar and running maven.

I do get a repl and navigate to localhost:8080 fine but if I click on a link I get:

]  script/repl 
Clojure 1.2.0-master-SNAPSHOT
2010-10-18 16:27:48.534::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2010-10-18 16:27:48.536::INFO:  jetty-6.1.14
2010-10-18 16:27:48.566::INFO:  Started SocketConnector@0.0.0.0:9000
2010-10-18 16:27:48.566::INFO:  jetty-6.1.14
2010-10-18 16:27:48.568::INFO:  Started SocketConnector@0.0.0.0:8080
Welcome to the labrepl. Browse to localhost:8080 to get started!
user=> 2010-10-18 16:28:04.885::WARN:  EXCEPTION 
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.Named
    at clojure.core$name.invoke(core.clj:1229)
    at labrepl.lab$instructions.invoke(lab.clj:22)
    at labrepl$fn__1831$fn__1832.invoke(labrepl.clj:40)
    at compojure.core$routes$fn__727$fn__728.invoke(core.clj:72)
    at clojure.core$some.invoke(core.clj:2037)
    at compojure.core$routes$fn__727.invoke(core.clj:72)
    at ring.middleware.params$wrap_params$fn__423.invoke(params.clj:77)
    at ring.middleware.cookies$wrap_cookies$fn__519.invoke(cookies.clj:123)
    at labrepl$with_logging$fn__1813.invoke(labrepl.clj:17)
    at compojure.core$routes$fn__727$fn__728.invoke(core.clj:72)
    at clojure.core$some.invoke(core.clj:2037)
    at compojure.core$routes$fn__727.invoke(core.clj:72)
    at ring.middleware.params$wrap_params$fn__423.invoke(params.clj:77)
    at ring.middleware.cookies$wrap_cookies$fn__519.invoke(cookies.clj:123)
    at compojure.core$routes$fn__727$fn__728.invoke(core.clj:72)
    at clojure.core$some.invoke(core.clj:2037)
    at compojure.core$routes$fn__727.invoke(core.clj:72)
    at ring.middleware.params$wrap_params$fn__423.invoke(params.clj:77)
    at ring.middleware.cookies$wrap_cookies$fn__519.invoke(cookies.clj:123)
    at clojure.lang.Var.invoke(Var.java:365)
    at ring.adapter.jetty$proxy_handler$fn__1478.invoke(jetty.clj:16)
    at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:864)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:533)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:207)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:403)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:522)

**Comment by rabid-fish** [comment]
I'm a total clojure noob trying to get this all to work, and dangit if this issue didn't cause me to waste two hours. Here's my fix for project.clj:

:dev-dependencies [[autodoc "0.7.1" :exclusions [ org.clojure/clojure-contrib ]]

Then a publicly unavailable clojure-contrib no longer blocks lein deps.

**Comment by alexrobbins** [comment]
I haven't worked my way through all the labs yet, but I think you can drop all the dev dependencies if you are just trying to run the labs. (At least, that that seems like it should be the case. If they are needed just to run the lab, then they aren't really dev-dependencies.)

**Comment by abedra** [comment]
This issue has been resolved
