### ISSUE TITLE
maven dependency issue

### ISSUE THREAD

**Issue by madhu314** [relevance/labrepl#48]
I followed the instructions mentioned in eclipse section to install labrepl.....after running the project in closure repl, I always get a class not found exception. It might be that there is some dependency missing in maven project.
=> (require 'labrepl) 
# ClassNotFoundException java.lang.ClassNotFoundException: org.mortbay.jetty.handler.AbstractHandler

When i took close look at maven logs, I found that closure maven plugin failed to compile..here is he snippet of maven output

Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.1:compile (default-cli) on project labrepl: Clojure failed. -> [Help 1]

Exception in thread "main" java.lang.ClassNotFoundException: org.mortbay.jetty.handler.AbstractHandler, compiling:(jetty.clj:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3228)
    at clojure.lang.Compiler.compile1(Compiler.java:6733)
    at clojure.lang.Compiler.compile1(Compiler.java:6723)
    at clojure.lang.Compiler.compile(Compiler.java:6794)
    at clojure.lang.RT.compile(RT.java:368)
    at clojure.lang.RT.load(RT.java:407)
    at clojure.lang.RT.load(RT.java:381)
    at clojure.core$load$fn__4389.invoke(core.clj:5308)

**Comment by abedra** [comment]
This issue has been resolved as of the latest commit

**Comment by wuzesheng** [comment]
Hi @abedra , can you give some details on how this issue was fixed, thanks very much?
